<?php

namespace Database\Seeders;

use App\Artikel;
use Illuminate\Database\Seeder;

class ArtikelSeeder extends Seeder
{
    public function run()
    {
        $artikel = Artikel::create([
            'title'         => 'Cari Kerja Terasa Sulit? Mungkin, Kamu Perlu Tips Ini',
            'image'         => '',
            'des_singkat'   => 'Belum punya pengalaman kerja, tentu akan menyulitkan seseorang untuk mendapatkan pekerjaan. Kamu bisa lakukan tips ini agar lebih berpotensi diterima kerja.',
            'des1'          => 'Tips Cari Kerja – Sudah bukan lagi hal yang aneh bila mencari pekerjaan memang menjadi sebuah tantangan tersendiri bagi para pencarinya.',
            'des2'          => 'Penolakan kerja berulang-ulang tentunya menjadi sebuah beban bagi para pencari kerja. Khususnya fresh graduate yang masih minim pengalaman kerja.',
            'des3'          => 'Kondisi seperti ini sudah jelas akan membuat cari kerja terasa sulit dan terbebani. Apalagi, jika sudah berbulan-bulan tak dapat pekerjaan.',
            'des4'          => 'Namun, semua itu bukan menjadi alasan. Karena, ada beberapa upaya atau tips yang bisa kamu lakukan untuk mempermudah kamu mencari kerja.',
            'des5'          => 'Dimana, tips ini cukup efektif dalam mendapatkan lowongan kerja secara mudah, sesuai bidangnya, dan mudah dalam mengajukan pelamaran.',
            'des6'          => 'Untuk lebih jelasnya, mari kita simak bersama bagaimana tips yang tepat untuk mencari kerja yang terasa sulit dan susah.',
            'des7'          => '',
            'judul_singkat' => 'Tips Cari Kerja',
            'penghantar'    => 'Tak perlu bingung belum dapat kerja. Ada tips efektif mencari kerja yang tepat jika kamu merasa sulit mencari lowongan. Berikut tips yang bisa kamu terapkan.',
            'judulisi1'     => '1 . Cari Lowongan di Situs Resmi',
            'isi11'         => 'Pertama, sudah jelas buat kamu yang kesulitan cari kerja, kamu bisa coba untuk mencari lowongan kerja di situs resmi perusahaan pengiklan loker.',
            'isi12'         => 'Cara ini jauh lebih efektif dan tak akan membuang-buang waktumu dalam mencari loker. Sehingga, kamu bisa memanfaatkan waktu lebih efisien.',
            'isi13'         => 'Namun, sebaiknya gunakan situs penyedia iklan loker resmi yang sudah memiliki kredibilitas tinggi sebagai penyedia info lowongan kerja.',
            'isi14'         => 'Langkah ini untuk mencegah atau menghindari modus penipuan yang berkedok lowongan pekerjaan. Dengan begitu maka kamu akan lebih mudah menyaring mana lowongan yang benar-benar dan mana info loker menyesatkan.',
            'isi15'         => '',
            'isi16'         => '',
            'judulisi2'     => '2. Ajukan Lamaran di Lowongan Seadanya',
            'isi21'         => 'Jika kamu masih belum juga mendapat pekerjaan, kamu bisa mencoba untuk keluar dari zona nyamanmu, yaitu dengan mengajukan lamaran di bidang pekerjaan yang mungkin saja tak cocok dengan keahlianmu.',
            'isi22'         => 'Langkah ini tentu sebagai salah satu batu loncatan sebelum kamu melamar di perusahaan yang sesuai dengan keahlian atau bidang kamu.',
            'isi23'         => 'Setidaknya, sambil mendapatkan pengalaman di dunia kerja, cara seperti ini juga efektif untuk mendapatkan sumber penghasilan. Meskipun tak seberapa namun bisa kamu jadikan uang saku atau persiapan saat kamu mulai mencari lowongan yang sesuai minat maupun kemampuanmu.',
            'isi24'         => '',
            'isi25'         => '',
            'isi26'         => '',
            'judulisi3'     => '3. Perbaiki CV yang Lebih Profesional',
            'isi31'         => 'Di sisi lain, bila ada kesulitan kamu dalam mendapatkan pekerjaan, tentu saja kamu bisa mencoba untuk meneliti kembali dan memperbaiki CV.',
            'isi32'         => 'Karena, bisa jadi bukan karena kamu sulit mencari kerja, tapi lebih kepada sulit untuk diterima perusahaan. Hal ini juga bisa saja dipengaruhi dari kualitas CV kamu yang kurang menarik di mata perusahaan.',
            'isi33'         => '',
            'isi34'         => '',
            'isi35'         => '',
            'isi36'         => '',
            'judulisi4'     => '4. Cari Info Loker di Situs yang Langsung Lamar',
            'isi41'         => 'Maksudnya, untuk mempermudah kamu dalam mencari kerja agar tidak sulit, kamu bisa mencari situs resmi penyedia iklan lowongan kerja yang menyediakan kemudahan dalam pengajuan lamaran.',
            'isi42'         => 'Biasanya, akan ada navigasi dalam situs tersebut yang menawarkan kamu untuk mengajukan surat lamaran untuk nanti diteruskan ke pihak perusahaan oleh situs tersebut.',
            'isi43'         => 'Langkah ini jauh lebih simple daripada kamu harus mengajukan secara mandiri. Jadi, cukup mengupload file CV dan berkas lamaran dalam bentuk PDF. Selanjutnya, kamu tinggal menunggu panggilan kerja jika lolos verifikasi.',
            'isi44'         => 'Nah, khusus buat kamu yang ingin mendapatkan loker Jogja dengan navigasi pengajuan lamaran langsung via website, kamu bisa merujuk ke situs LokerJogja.ID dengan ragam jenis info lowongan terbaru.',
            'isi45'         => '',
            'isi46'         => '',
            'judulisi5'     => '',
            'isi51'         => '',
            'isi52'         => '',
            'isi53'         => '',
            'isi54'         => '',
            'isi55'         => '',
            'isi56'         => '',
        ]);
        $artikel->save();

        $artikel = Artikel::create([
            'title'         => 'Tips Hadapi Rasa Malas saat Bekerja',
            'image'         => '',
            'des_singkat'   => 'Hadapi rasa malas dalam bekerja dengan beberapa langkah sederhana agar bekerja menjadi lebih semangat',
            'des1'          => 'Hadapi Rasa Malas saat Kerja – Tak bisa dipungkiri bahwa hampir setiap karyawan tentu pernah mengalami rasa malas yang sangat ketika sedang bekerja.',
            'des2'          => 'Perasaan seperti ini memang wajar terjadi yang biasanya dikarenakan faktor lingkungan monoton ataupun karena sebab eksternal.',
            'des3'          => 'Namun, bila rasa malas terus saja muncul saat kamu sedang bekerja, jelas itu menjadi sebuah masalah yang memerlukan solusi sebagai jalan keluarnya.',
            'des4'          => 'Dimana, dalam hal ini tentu saja diperlukan beberapa langkah efektif, setidaknya untuk meminimalisir rasa bosan ataupun malas yang terkadang datang menghampiri begitu saja ketika kamu tengah melakukan pekerjaan kantor.',
            'des5'          => 'Nah, berikut ada beberapa tips yang bisa kamu coba untuk membuang rasa malas agar nantinya pekerjaan bisa diselesaikan dengan cepat dan tepat waktu.',
            'des6'          => '',
            'des7'          => '',
            'judul_singkat' => 'Cara Hadapi Rasa Malas saat Kerja',
            'penghantar'    => 'Dalam kaitannya dengan rasa malas dalam bekerja, tentu ada beberapa trik yang bisa kamu coba untuk menghalau perasaan malas. Berikut penjelasannya.',
            'judulisi1'     => '1 . Ingat untuk Bersyukur',
            'isi11'         => 'Pertama dan harus dipaksa untuk diingat adalah selalu bersyukur bahwa kamu memiliki pekerjaan sebagai sumber pendapatan untuk menunjang kebutuhan hidup.',
            'isi12'         => 'Jika rasa malas tiba-tiba menghinggapimu, cobalah untuk melihat di sekelilingmu. Masih banyak pengangguran yang ingin mendapatkan pekerjaan namun tidak juga kunjung diterima kerja.',
            'isi13'         => 'Masih banyak orang yang tak mampu lagi bekerja karena sudah tidak sanggup lagi melakukan pekerjaan berat dikarenakan kesehatan atau faktor lain.',
            'isi14'         => 'Nah, dari situ tentu kamu lebih bisa bersyukur bahwa kamu masih memiliki pekerjaan yang layak dan gaji yang bisa untuk kamu gunakan sebagai sumber dalam menunjang kebutuhan hidup.',
            'isi15'         => 'Dimana, gaji tersebut tentu diinginkan oleh banyak orang para penggangguran di sana. So, jangan patah semangat dan teruslah untuk bersemangat dalam bekerja.',
            'isi16'         => '',
            'judulisi2'     => '2. Beri Waktu Sedikit untuk Tenangkan Pikiran',
            'isi21'         => 'Biasanya, rasa malas dalam bekerja timbul karena kondisi lingkungan yang monoton ataupun karena beban pekerjaan yang selalu saja menghampiri.',
            'isi22'         => 'Jika memang benar demikian, cobalah sejenak mencari waktu luang sedikit saja di kantor untuk keluar sebentar dan tenangkan pikiranmu.',
            'isi24'         => 'Kamu juga bisa mencoba untuk mengobrol bersama rekan kerja saat waktu istirahat guna menghilangkan rasa penat karena pekerjaan yang membuatmu merasa malas dalam melakukan pekerjaan tersebut.',
            'isi25'         => 'Hal ini perlu dilakukan sebagai tindakan guna membuang rasa malas dalam bekerja dikarenakan faktor pekerjaan yang terlalu monoton.',
            'isi26'         => '',
            'judulisi3'     => '3. Gunakan Waktu Libur untuk Refreshing',
            'isi31'         => 'Kebiasaan di kantor yang setiap hari melakukan pekerjaan yang sama, tentu membuat kamu meras bosan dan akan memicu rasa malas.',
            'isi32'         => 'Untuk itu, manfaatkan waktu liburkan untuk refreshing bersama keluarga ataupun pasangan ke tempat wisata.',
            'isi33'         => 'Sebaiknya, waktu libur jangan digunakan untuk bekerja namun lebih baik dimanfaatkan untuk merefrsh pikiran dengan melakukan aktivitas mengasyikan.',
            'isi34'         => 'Nah, dari hal ini, tentu saja kamu akan merasa lebih fresh ketika esoknya masuk kerja dengan semangat yang lebih baru.',
            'isi35'         => '',
            'isi36'         => '',
            'judulisi4'     => '4. Bikin Minuman Favorit',
            'isi41'         => 'Umumnya, bagi sebagian orang membuat minuman favorit di kala sedang bekerja menjadi salah satu cara untuk menghilangkan rasa bosan dan malas.',
            'isi42'         => 'Misalnya saja, jika kamu suka kopi maka saat rasa malas datang menghampiri, maka kamu bisa membuat kopi untuk sekedar merelaksasi pikiranmu.',
            'isi43'         => 'Dengan begitu maka rasa malas lambat laun akan menghilang melalui seduhan minuman avorit kamu.',
            'isi44'         => 'Untuk mendapatkan info terkini mengenai lowongan kerja Jogja, kamu bisa mengunjungi situs LokerJogja.ID yang menyajikan berbagai info lowongan pekerjaan terbaru.',
            'isi45'         => '',
            'isi46'         => '',
            'judulisi5'     => '',
            'isi51'         => '',
            'isi52'         => '',
            'isi53'         => '',
            'isi54'         => '',
            'isi55'         => '',
            'isi56'         => '',
        ]);
        $artikel->save();

        $artikel = Artikel::create([
            'title'         => 'Catat! Hindari Beberapa Hal Ini agar Kamu Lolos Tes Kerja',
            'image'         => '',
            'des_singkat'   => 'Hal-hal penting yang perlu dihindari supaya bisa diterima kerja oleh perusahaan',
            'des1'          => 'Agar Lolos Tes Kerja – Dalam langkah persiapan tes masuk kerja, sudah barang tentu kamu harus mempersiapkan diri agar bisa menghadapinya.',
            'des2'          => 'Namun, tak jarang dari beberapa orang yang kurang bisa memahami apa saja persiapan paling penting dan pokok sebelum menghadapi tes kerja.',
            'des3'          => 'Karena, tak hanya soal bisa atau tidaknya menjawab wawancara maupun bisa mengerjakan soal tes masuk kerja. Melainkan lebih kepada bagaimana kamu bisa melalui setiap tahap demi tahap tes secara fair dengan tips tepat agar perusahaan tertarik untuk merekrut.',
            'des4'          => 'Dimana, kamu perlu menerapkan berbagai langkah konkrit guna menjaga performa kamu dalam menjalani berbagai tes agar lebih mudah diterima di perusahaan yang kamu lamar tersebut.',
            'des5'          => 'Namun, di sisi lain kamu juga perlu untuk memahami apa saja hal-hal penting yang patut dihindari saat tes masuk kerja.',
            'des6'          => 'Nah, berikut ini akan dijelaskan hal-hal yang perlu dihindari agar lolos masuk kerja. Yuk, kita simak bersama tips lengkapnya.',
            'des7'          => '',
            'judul_singkat' => 'Tips agar Diterima Kerja',
            'penghantar'    => 'Di antara beberapa tips, ada beberapa aspek yang tidak perlu untuk Anda lakukan saat tengah menjalani tes masuk kerja. Berikut beberapa di antaranya,',
            'judulisi1'     => '1 . Ingat untuk Bersyukur',
            'isi11'         => 'Pertama dan harus dipaksa untuk diingat adalah selalu bersyukur bahwa kamu memiliki pekerjaan sebagai sumber pendapatan untuk menunjang kebutuhan hidup.',
            'isi12'         => 'Jika rasa malas tiba-tiba menghinggapimu, cobalah untuk melihat di sekelilingmu. Masih banyak pengangguran yang ingin mendapatkan pekerjaan namun tidak juga kunjung diterima kerja.',
            'isi13'         => 'Masih banyak orang yang tak mampu lagi bekerja karena sudah tidak sanggup lagi melakukan pekerjaan berat dikarenakan kesehatan atau faktor lain.',
            'isi14'         => 'Nah, dari situ tentu kamu lebih bisa bersyukur bahwa kamu masih memiliki pekerjaan yang layak dan gaji yang bisa untuk kamu gunakan sebagai sumber dalam menunjang kebutuhan hidup.',
            'isi15'         => 'Dimana, gaji tersebut tentu diinginkan oleh banyak orang para penggangguran di sana. So, jangan patah semangat dan teruslah untuk bersemangat dalam bekerja.',
            'isi16'         => '',
            'judulisi2'     => '2. Beri Waktu Sedikit untuk Tenangkan Pikiran',
            'isi21'         => 'Biasanya, rasa malas dalam bekerja timbul karena kondisi lingkungan yang monoton ataupun karena beban pekerjaan yang selalu saja menghampiri.',
            'isi22'         => 'Jika memang benar demikian, cobalah sejenak mencari waktu luang sedikit saja di kantor untuk keluar sebentar dan tenangkan pikiranmu.',
            'isi24'         => 'Kamu juga bisa mencoba untuk mengobrol bersama rekan kerja saat waktu istirahat guna menghilangkan rasa penat karena pekerjaan yang membuatmu merasa malas dalam melakukan pekerjaan tersebut.',
            'isi25'         => 'Hal ini perlu dilakukan sebagai tindakan guna membuang rasa malas dalam bekerja dikarenakan faktor pekerjaan yang terlalu monoton.',
            'isi26'         => '',
            'judulisi3'     => '3. Gunakan Waktu Libur untuk Refreshing',
            'isi31'         => 'Kebiasaan di kantor yang setiap hari melakukan pekerjaan yang sama, tentu membuat kamu meras bosan dan akan memicu rasa malas.',
            'isi32'         => 'Untuk itu, manfaatkan waktu liburkan untuk refreshing bersama keluarga ataupun pasangan ke tempat wisata.',
            'isi33'         => 'Sebaiknya, waktu libur jangan digunakan untuk bekerja namun lebih baik dimanfaatkan untuk merefrsh pikiran dengan melakukan aktivitas mengasyikan.',
            'isi34'         => 'Nah, dari hal ini, tentu saja kamu akan merasa lebih fresh ketika esoknya masuk kerja dengan semangat yang lebih baru.',
            'isi35'         => '',
            'isi36'         => '',
            'judulisi4'     => '4. Bikin Minuman Favorit',
            'isi41'         => 'Umumnya, bagi sebagian orang membuat minuman favorit di kala sedang bekerja menjadi salah satu cara untuk menghilangkan rasa bosan dan malas.',
            'isi42'         => 'Misalnya saja, jika kamu suka kopi maka saat rasa malas datang menghampiri, maka kamu bisa membuat kopi untuk sekedar merelaksasi pikiranmu.',
            'isi43'         => 'Dengan begitu maka rasa malas lambat laun akan menghilang melalui seduhan minuman avorit kamu.',
            'isi44'         => 'Untuk mendapatkan info terkini mengenai lowongan kerja Jogja, kamu bisa mengunjungi situs LokerJogja.ID yang menyajikan berbagai info lowongan pekerjaan terbaru.',
            'isi45'         => '',
            'isi46'         => '',
            'judulisi5'     => '',
            'isi51'         => '',
            'isi52'         => '',
            'isi53'         => '',
            'isi54'         => '',
            'isi55'         => '',
            'isi56'         => '',
        ]);
        $artikel->save();
    }
}
